markdown: kramdown
permalink: pretty
exclude: [README.md, Gemfile, Gemfile.lock, repo-metadata.html]

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs"
      categories: "docs"
  -
    scope:
      path: "docs/drivers"
      type: "pages"
    values:
      category: "drivers"
  -
    scope:
      path: "docs/tutorials"
      type: "pages"
    values:
      category: "tutorials"
  -
    scope:
      path: "docs/sensors"
      type: "pages"
    values:
      category: "sensors"
  -
    scope:
      path: "docs/motors"
      type: "pages"
    values:
      category: "motors"
  -
    scope:
      path: "docs/devtools"
      type: "pages"
    values:
      category: "devtools"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: "project"
  -
    scope:
      path: "news"
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "javascripts"
      type: "pages"
    values:
      layout: "none"
      
kramdown:
    toc_levels: "2,3"
